site_name: Config-Segregate Documentation
repo_url: https://github.com/ross-tsenov/config-segregate
repo_name: config-segregate
theme:
  name: material
  language: en
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: black
    accent: deep purple
    font:
      text: Roboto
      code: Roboto Mono
  features:
    - navigation.top
    - navigation.sections
    - navigation.instant
    - content.code.annotate

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
