name: Publish

on:
  # push:
  #   tags:
  #     - '*'
  pull_request:
    branches: [ main ]

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    environment:
      name: Deploy to PyPi and Github Pages

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true

      # - name: Publish to PyPI & deploy docs
      #   run: |
      #     poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
      #     poetry publish --build

      - name: Deploy GitHub Pages Docs
        run: |
          git config user.name "GitHub Action"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          poetry install --only docs --no-interaction
          source $VENV
          mkdocs gh-deploy --force
